# Generated by Django 4.2 on 2025-06-26 16:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='tipologia',
            field=django_mysql.models.EnumField(choices=[('singola', 'Singola'), ('doppia', 'Doppia'), ('matrimoniale', 'Matrimoniale'), ('suite', 'Suite')], default='singola'),
        ),
        migrations.AlterField(
            model_name='eventolocale',
            name='titolo',
            field=django_mysql.models.EnumField(choices=[('degustazione', 'Degustazione'), ('escursione', 'Escursione'), ('visita guidata', 'Visita Guidata'), ('serata a tema', 'Serata Tema')], default='degustazione'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=django_mysql.models.EnumField(choices=[('in attesa', 'Attesa'), ('confermata', 'Confermata'), ('annullata', 'Annullata'), ('completata', 'Completata')], default='in attesa'),
        ),
        migrations.AlterField(
            model_name='servizioextra',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('colazione', 'Colazione'), ('navetta', 'Navetta'), ('spa', 'Spa'), ('escursione', 'Escursione')], default='colazione'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=django_mysql.models.EnumField(choices=[('Cliente', 'Cliente'), ('Staff', 'Staff'), ('Gestore', 'Gestore')], default='Cliente'),
        ),
    ]
