# Generated by Django 4.2 on 2025-06-26 22:06

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0002_alter_camera_tipologia_alter_eventolocale_titolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizioextra',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('colazione', 'Colazione'), ('navetta', 'Navetta'), ('spa', 'Spa'), ('escursione', 'Escursione'), ('culla', 'Culla'), ('letto aggiuntivo', 'Letto Aggiuntivo')], default='colazione'),
        ),
    ]
