# Generated by Django 4.2 on 2025-06-27 01:02

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0003_alter_servizioextra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=django_mysql.models.EnumField(choices=[('in attesa', 'Attesa'), ('confermata', 'Confermata'), ('in corso', 'In Corso'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='in attesa'),
        ),
    ]
